
POST  http://localhost:8080/api/v1/register
Content-Type: application/json

{
  "email": "sandy4@gmail.com",
  "name": "test4",
  "password": "Secret1235",
  "passwordConfirmation": "Secret1235"
}

###

POST  http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "email": "sandy4@gmail.com",
  "password": "Secret1235"
}

###

POST  http://localhost:8080/api/v1/logout
Content-Type: application/json

{
   "email": "sandy4@gmail.com",
  "password": "Secret1235"
}

